// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArADf57SHliMuSiU7mf1ILITMf2pyBa6k',
    appId: '1:854903352082:web:be290ecf319f026823e1cb',
    messagingSenderId: '854903352082',
    projectId: 'tugasakhir-c7b7b',
    authDomain: 'tugasakhir-c7b7b.firebaseapp.com',
    databaseURL: 'https://tugasakhir-c7b7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasakhir-c7b7b.appspot.com',
    measurementId: 'G-6ZM4MFHYBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgia8IgdHQQfTFg-yCDTE4rCw5JXw1ko0',
    appId: '1:854903352082:android:2abe763581b19c1223e1cb',
    messagingSenderId: '854903352082',
    projectId: 'tugasakhir-c7b7b',
    databaseURL: 'https://tugasakhir-c7b7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasakhir-c7b7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtKqkucuoANFP83tLiq4_qOehW9yAy-_E',
    appId: '1:854903352082:ios:82d7d119a80aa76a23e1cb',
    messagingSenderId: '854903352082',
    projectId: 'tugasakhir-c7b7b',
    databaseURL: 'https://tugasakhir-c7b7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasakhir-c7b7b.appspot.com',
    iosBundleId: 'com.ainisapplication.app.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtKqkucuoANFP83tLiq4_qOehW9yAy-_E',
    appId: '1:854903352082:ios:74f93370c48e2b9623e1cb',
    messagingSenderId: '854903352082',
    projectId: 'tugasakhir-c7b7b',
    databaseURL: 'https://tugasakhir-c7b7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasakhir-c7b7b.appspot.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArADf57SHliMuSiU7mf1ILITMf2pyBa6k',
    appId: '1:854903352082:web:6f2f3de879ad6d5d23e1cb',
    messagingSenderId: '854903352082',
    projectId: 'tugasakhir-c7b7b',
    authDomain: 'tugasakhir-c7b7b.firebaseapp.com',
    databaseURL: 'https://tugasakhir-c7b7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasakhir-c7b7b.appspot.com',
    measurementId: 'G-0WJ725ESLM',
  );
}
